const pc_sewa = () => {
return `SEWA BOT BY IKY BOT

*PERMINGGU=5K*
*PERBULAN=7K*
*PREMIUM+PERMANEN=15K*
*PERHARI=2K*

MURID BOT WA=20K

_ALL FITUR ON SMUA_

*ORDER? wa.me//6287874637761*

*UNTUK WA BOTNYA NANTI AKAN MASUK GC MELALUI INVIT*

*INGATT!*

*BOT TIDAK BOLEH DI PERMAINKAN*

*PERHATIKAN PP/ INFO WA BOT*

*WAJIB TIDAK BOLEH UNTUK DI PAKAI UNTUK YG ANEH²*

*MOHON TIDAK BEREBUT AGAR BOT TIDAK DELAY/TERBLOKIR*


NOTE : 
Bot On 24 Jam Karna Di Run Menggunakan Heroku
Reset Data Setiap Jam 02:00 `
	}



exports.pc_sewa = pc_sewa
